#
# Netlify CMS
#

backend:
  name: git-gateway
  repo: akvadrako/site-xyz
  branch: master
collections:
  - name: routes
    label: routes
    label_singular: route
    folder: 'src/routes/[lang]'
    extension: mdx
    format: yaml-frontmatter
    create: true
    fields:
      - name: title
      #- name: layout
      - name: body
        widget: markdown
  - name: works
    #i18n: true
    label: works
    label_singular: work
    folder: 'src/routes/[lang]/works'
    extension: mdx
    format: yaml-frontmatter
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - name: slug
        label: slug (short, unique ID for URL path)
      - name: title_en
        label: English Title
      - name: title_nl
        label: Dutch Title
      - name: layout
        widget: hidden
        default: work
      - name: date
        widget: date
      - name: image
        widget: image
        allow_multiple: false
      - name: body
        widget: markdown
        label: Page Content / Description
media_folder: "static/media"
public_folder: "/media"

local_backend: true

# i18n:
#   structure: single_file
#   locales: [en, nl]
#   default_locale: en

# publish_mode: editorial_workflow

site_url: https://lucid-hodgkin-cc7294.netlify.app
logo_url: https://lucid-hodgkin-cc7294.netlify.app/media/logo.svg

# display_url: https://your-site.com

