backend:
  name: git-gateway
  branch: master
collections:
  - name: routes
    label: routes
    label_singular: route
  - name: pages
    folder: src/routes/pages
    create: true
    nested:
      depth: 10
      summary: '{{title}}'
    fields:
      - name: title
      - name: nav_label
      - name: body
        widget: markdown
    meta:
      path: { widget: string, label: 'Path', index_file: 'index' }
  - name: posts
    label: Posts
    folder: src/routes/posts
    create: true
    slug: "{{year}}/{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
media_folder: "static/uploads"
public_folder: "/uploads"

# publish_mode: editorial_workflow

# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg
