#
# Netlify CMS
#
# Note: symlinks will result in SHA errors
#
# see https://www.staticcms.org/docs/configuration-options
#

media_folder: "static/media"
public_folder: "/media"
local_backend: true

site_url: https://walltowall.nl
logo_url: https://walltowall.nl/media/logo.svg
display_url: https://walltowall.nl

i18n:
  structure: multiple_files
  locales: [en, nl]
  default_locale: en

backend:
  #name: git-gateway
  name: github
  repo: akvadrako/site-xyz
  branch: master

collections:
  - name: blog
    label: blog
    label_singular: blog
    folder: 'doc/blog'
    extension: md
    format: yaml-frontmatter
    create: true
    i18n: false
    slug: "{{title_en}}"
    preview_path: "/en/blog/{{slug}}"
    fields:
      - name: title_en
      - name: title_nl
      - name: date
        widget: date
      - name: image
        label: Main Image
        widget: image
        allow_multiple: false
      - name: body
        widget: markdown
  - name: blurbs
    label: blurbs
    label_singular: blurbs
    folder: 'doc/blurbs'
    extension: md
    format: yaml-frontmatter
    create: true
    i18n: true
    fields:
      - name: title
      - name: body
        widget: markdown
  - name: pages
    label: pages
    label_singular: page
    folder: 'doc/pages'
    extension: md
    format: yaml-frontmatter
    create: true
    slug: "{{title_en}}"
    preview_path: "/en/{{slug}}"
    fields:
      - name: title_en
      - name: title_nl
      - name: body
        widget: markdown
  - name: works
    label: works
    label_singular: work
    folder: 'doc/works'
    extension: md
    format: yaml-frontmatter
    create: true
    slug: "{{title_en}}"
    preview_path: "/en/works/{{slug}}"
    fields:
      - name: kind
        widget: select
        options: ['illustration', 'mural', 'painting']
      - name: title_en
        label: English Title
      - name: title_nl
        label: Dutch Title
      - name: layout
        widget: hidden
        default: work
      - name: date
        widget: date
      - name: image
        label: Primary Image
        widget: image
        allow_multiple: false
      - name: more_images
        label: Secondary Images
        widget: list
        summary: '{{fields.image}}'
        field:
          name: image
          widget: image
          allow_multiple: false
      - name: body
        widget: markdown
        label: Page Content / Description

