#
# Netlify CMS
#

media_folder: "static/media"
public_folder: "/media"
local_backend: true

site_url: /
logo_url: https://walltowall.nl/media/logo.svg
display_url: /

backend:
  name: git-gateway
  repo: akvadrako/site-xyz
  branch: master

collections:
  - name: pages
    label: pages
    label_singular: page
    folder: 'src/pages'
    extension: mdx
    format: yaml-frontmatter
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - name: slug
        label: slug (short, unique ID for URL path)
      - name: title_en
      - name: title_nl
      - name: body
        widget: markdown
  - name: works
    label: works
    label_singular: work
    folder: 'src/works'
    extension: mdx
    format: yaml-frontmatter
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    preview_path: "/en/works/{{slug}}"
    fields:
      - name: slug
        label: slug (short, unique ID for URL path)
      - name: kind
        widget: select
        options: ['illustration', 'mural', 'painting']
      - name: title_en
        label: English Title
      - name: title_nl
        label: Dutch Title
      - name: layout
        widget: hidden
        default: work
      - name: date
        widget: date
      - name: image
        label: Primary Image
        widget: image
        allow_multiple: false
      - name: more_images
        label: Secondary Images
        widget: list
        summary: '{{fields.image}}'
        field:
          name: image
          widget: image
          allow_multiple: false
      - name: body
        widget: markdown
        label: Page Content / Description

